[project]
name = "application-package-patterns"
version = "1.0.0"

[build]
engine = "cluster"

[build.local]
runtime="docker"
registry="cr.terradue.com/earthquake-monitoring"

[build.cluster]
namespace = "eoap-application-package-patterns"
serviceAccount = "kaniko-sa"
registry = "cr.terradue.com/earthquake-monitoring"
secret = "kaniko-secret"


[[workflows]]
path = "wrapped-cwl-workflow/pattern-1.cwl"

[[workflows.tests]]
name = "pattern-1-test"
description = "Test case for pattern-1"

[workflows.tests.params]
tif = "https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/10/T/FK/2021/7/S2B_10TFK_20210713_0_L2A/TCI.tif"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/pattern-1"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"


[[workflows]]
path = "wrapped-cwl-workflow/pattern-2.cwl"

[[workflows.tests]]
name = "pattern-1-test"
description = "Test case for pattern-2"

[workflows.tests.params]
tif = "https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/10/T/FK/2021/7/S2B_10TFK_20210713_0_L2A/TCI.tif"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/how-to/capture-stdout"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"



[[workflows]]
path = "cwl-workflows/capture-json-stdout.cwl"

[[workflows.tests]]
name = "capture-json-stdout-test"
description = "Test case for capture json stdout"

[workflows.tests.params]
stac-item = "https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_53HPA_20210723_0_L2A"
common-band-name = "red"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/how-to/capture-json-stdout"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"




[[workflows]]
path = "cwl-workflows/environment-variable.cwl"

[[workflows.tests]]
name = "environment-variable-test"
description = "Test case for environment variables"

[workflows.tests.params]
stac-item = "https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_53HPA_20210723_0_L2A"
bands = ["red", "green", "blue" ]

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/how-to/environment-variable"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"



[[workflows]]
path = "cwl-workflows/runtime-file.cwl"

[[workflows.tests]]
name = "runtime-file-test"
description = "Test case for runtime files"

[workflows.tests.params]
stac-item = "https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_53HPA_20210723_0_L2A"
bands = ["red", "green", "blue" ]

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/how-to/runtime-file"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"


[[workflows]]
path = "cwl-workflows/nested-workflow.cwl"

[[workflows.tests]]
name = "nested-workflow-test"
description = "Test case for nested workflows"

[workflows.tests.params]
stac-item = "https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_53HPA_20210723_0_L2A"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/how-to/nested-workflow"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"



[[workflows]]
path = "cwl-workflows/scatter-workflows.cwl"

[[workflows.tests]]
name = "scatter-workflows-test"
description = "Test case for scatter workflows"

[workflows.tests.params]
stac-items = ["https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_53HPA_20210723_0_L2A", "https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_53HPA_20210728_0_L2A"]
bands = ["red", "green", "blue" ]

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/how-to/scatter-workflows"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"



[[workflows]]
path = "cwl-workflows/conditional-workflows.cwl"

[[workflows.tests]]
name = "conditional-workflows-test-native"
description = "Test case for conditional-workflows - native"

[workflows.tests.params]
"stac-item" = "https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_53HPA_20210723_0_L2A"
"bands" = ["red", "green", "blue" ]
"epsg_code" = "native"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/how-to/conditional-workflows-native"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"


[[workflows]]
path = "cwl-workflows/conditional-workflows.cwl"

[[workflows.tests]]
name = "conditional-workflows-test-epsg-4326"
description = "Test case for conditional-workflows - epsg:4326"

[workflows.tests.params]
"stac-item" = "https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_53HPA_20210723_0_L2A"
"bands" = ["red", "green", "blue" ]
"epsg_code" = "EPSG:4326"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/how-to/conditional-workflows-epsg-4326"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"


[[workflows]]
path = "cwl-workflows/scatter-input-parameters.cwl"

[[workflows.tests]]
name = "scatter-input-parameters-test"
description = "Test case for scatter input parameters"

[workflows.tests.params]
"stac-item" = "https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_53HPA_20210723_0_L2A"
"bands" = ["red", "green", "blue" ]
"epsg_code" = "EPSG:4326"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
pool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
tool_logs_basepath = "logs"

[workflows.tests.execution.paths]
volume = "/calrissian/how-to/scatter-input-parameters"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"